spring:
  profiles:
    active: development


---

spring:
  profiles: development
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/datacenter
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console/


---

spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://ccdb/datacenter
    username: ccuser
    password: ccuser
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update


